package com.dsh105.holoapi.image;

import java.awt.image.BufferedImage;

/**
 * Represents an animated frame generated by a GIF image
 */

public class GIFFrame extends Frame {

    protected BufferedImage image;
    protected String disposal;

    protected ImageGenerator imageGenerator;

    protected GIFFrame(BufferedImage image, int delay, String disposal) {
        super(delay);
        this.image = image;
        this.disposal = disposal;
    }

    protected GIFFrame(ImageGenerator generator, int delay) {
        super(delay);
        this.imageGenerator = generator;
    }

    /**
     * Gets the image generator used to generate the frame lines
     *
     * @return image generator used
     */
    public ImageGenerator getImageGenerator() {
        return imageGenerator;
    }

    @Override
    public String[] getLines() {
        return this.imageGenerator.getLines();
    }
}