name: ${project.name}
version: ${project.version}
author: [DSH105, CaptainBern]
description: Advanced Hologram management
softdepend: [Vault, VanishNoPacket]
website: ${project.url}
main: ${main.class}
version: ${project.version}
commands:
    holoupdate:
        description: Update the HoloAPI plugin
        permission: holoapi.update
permissions:
    holoapi.holo:
        default: op
    holoapi.holo.create:
        default: op
    holoapi.holo.remove:
        default: op
    holoapi.holo.info:
        default: op
    holoapi.holo.move:
        default: op
    holoapi.holo.teleport:
        default: op
    holoapi.holo.build:
        default: op
    holoapi.holo.reload:
        default: op
    holoapi.holo.edit:
        default: op
    holoapi.holo.refresh:
        default: op
    holoapi.holo.copy:
        default: op
    holoapi.holo.nearby:
        default: op
    holoapi.update:
        default: op
    holoapi.*:
        default: op
        description: All HoloAPI commands
        children:
            holoapi.holo: true
            holoapi.holo.create: true
            holoapi.holo.remove: true
            holoapi.holo.info: true
            holoapi.holo.reload: true
            holoapi.holo.move: true
            holoapi.holo.teleport: true
            holoapi.holo.build: true
            holoapi.holo.edit: true
            holoapi.holo.refresh: true
            holoapi.holo.copy: true
            holoapi.holo.nearby: true
            holoapi.update: true