name: ${project.name}
version: ${project.version}
author: [DSH105, CaptainBern]
description: Advanced Hologram Management
softdepend: [Vault, VanishNoPacket]
website: ${project.url}
main: com.dsh105.holoapi.HoloAPICore
version: ${project.version}
permissions:
    holoapi.holo:
        default: op
    holoapi.holo.create:
        default: op
    holoapi.holo.remove:
        default: op
    holoapi.holo.info:
        default: op
    holoapi.holo.move:
        default: op
    holoapi.holo.teleport:
        default: op
    holoapi.holo.build:
        default: op
    holoapi.holo.reload:
        default: op
    holoapi.holo.edit:
        default: op
    holoapi.holo.refresh:
        default: op
    holoapi.holo.copy:
        default: op
    holoapi.holo.nearby:
        default: op
    holoapi.holo.addline:
        default: op
    holoapi.holo.touch:
            default: op
    holoapi.holo.touch.add:
        default: op
    holoapi.holo.touch.remove:
        default: op
    holoapi.holo.touch.clear:
        default: op
    holoapi.holo.touch.info:
        default: op
    holoapi.holo.see.all:
        default: op
    holoapi.holo.visibility:
        default: op
    holoapi.holo.visibility.set:
        default: op
    holoapi.holo.readtxt:
        default: op
    holoapi.holo.show:
        default: op
    holoapi.holo.hide:
        default: op
    holoapi.update:
        default: op
    holoapi.*:
        default: op
        description: All HoloAPI commands
        children:
            holoapi.holo.touch.*: true
            holoapi.holo: true
            holoapi.holo.create: true
            holoapi.holo.remove: true
            holoapi.holo.info: true
            holoapi.holo.reload: true
            holoapi.holo.move: true
            holoapi.holo.teleport: true
            holoapi.holo.build: true
            holoapi.holo.edit: true
            holoapi.holo.refresh: true
            holoapi.holo.copy: true
            holoapi.holo.nearby: true
            holoapi.holo.addline: true
            holoapi.holo.see.all: true
            holoapi.holo.visibility: true
            holoapi.holo.visibility.set: true
            holoapi.holo.readtxt: true
            holoapi.holo.show: true
            holoapi.holo.hide: true
            holoapi.update: true
    holoapi.touch.*:
        default: op
        description: All HoloAPI commands under /holo touch
        children:
            holoapi.holo.touch: true
            holoapi.holo.touch.add: true
            holoapi.holo.touch.remove: true
            holoapi.holo.touch.clear: true
            holoapi.holo.touch.info: true